version: '3.4'
services:
  confluence:
    build:
      context: ./confluence
      dockerfile: Dockerfile
    container_name: confluence-srv
    environment:
      - TZ='Asia/Ho_Chi_Minh'
    depends_on:
      - confluencedb
    ports:
      - "8090:8090"
    volumes:
      - confluence_data:/var/confluence
      - confluence_core:/opt/confluence
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - network-bridge
  confluencedb:
    image: postgres:14
    container_name: postgresql-confluence
    env_file:
      - database-confluence.env
    # ports:
    #   - "5432:5432"
    volumes:
      - database-confluence:/var/lib/postgresql/data/
    restart: always
    networks:
      - network-bridge
networks:
  network-bridge:
    driver: bridge
volumes:
  database-confluence:
  confluence_data:
  confluence_core:
