version: '3.4'
services:
  confluence:
    image: vouu/confluence:build-05-10-2023
    container_name: confluence-srv
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - confluencedb
    ports:
      - "8090:8090"
    volumes:
      - home_data:/var/confluence
    restart: always
    networks:
      - network-bridge

  confluencedb:
    image: postgres:14
    container_name: postgresql-confluence
    env_file:
      - database-confluence.env
    # ports:
    #   - "5432:5432"
    volumes:
      - database-confluence:/var/lib/postgresql/data/
    restart: always
    networks:
      - network-bridge


networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
  database-confluence:
    external: false